version: "2.4"

services:
  db:
    image: postgres:13
    mem_limit: 300M
    memswap_limit: 300M
    cpu_shares: 200
    restart: "no"
    volumes:
      - ./postgres-initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - postgres.env
      - ofbiz-postgres.env

  ofbiz:
    image: ghcr.io/apache/ofbiz:experimental-docker-branch-plugins-snapshot
    mem_limit: 1600M
    memswap_limit: 1600M
    cpu_shares: 200
    ports:
      - 127.0.0.1:58009:8009
    env_file:
      - ofbiz-postgres.env
    environment:
      OFBIZ_HOST: exp3.ofbiz.apache.org
      OFBIZ_ENABLE_AJP_PORT: 1
      OFBIZ_DATA_LOAD: demo
