version: "2.4"

services:
  db:
    image: postgres:13
    mem_limit: 300M
    memswap_limit: 300M
    cpu_shares: 200
    restart: unless-stopped
    volumes:
      - ./postgres-initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - postgres.env
      - ofbiz-postgres.env

  ofbiz:
    image: ghcr.io/apache/ofbiz:release24.09-plugins-snapshot
    mem_limit: 2400M
    memswap_limit: 2400M
    cpu_shares: 200
    restart: unless-stopped
    ports:
      - 127.0.0.1:28009:8009
    volumes:
      - ./after-config-applied.d:/docker-entrypoint-hooks/after-config-applied.d
      # Note, on Unix systems, ensure the ofbiz user (uid 1000) or group (gid 1000) running inside the container has
      # write access to this directory on the host. If user namespace remapping is in use, the ofbiz user/group may
      # be mapped to host uid 165536 or gid 166536 depending on the configuration in /etc/subuid and /etc/subgid.
      - ./logs:/ofbiz/runtime/logs
    env_file:
      - ofbiz-postgres.env
    environment:
      OFBIZ_HOST: demo-next.ofbiz.apache.org
      OFBIZ_ENABLE_AJP_PORT: 1
      OFBIZ_DATA_LOAD: demo
      OFBIZ_CONTENT_URL_PREFIX: https://demo-next.ofbiz.apache.org
